### ISSUE TITLE
Support RDS v 3

### ISSUE THREAD

**Issue by programLyrique** [PRL-PRG/r-compile-server#17]
To populate a R session from installed R packages, we need to be able to read rdx and rdb files. 
They both use RDS and for the latest version of R, version 3.

I think we would need to support v3, without altrep as a start.

I started to look into it, and just removing the version check is not enough:

```java
Caused by: java.lang.IllegalArgumentException: Unknown RDS item type: 45
	at org.prlprg.rds.RDSItemType.valueOf(RDSItemType.java:38)
	at org.prlprg.rds.Flags.getType(Flags.java:61)
```

Just adding the reading of the encoding should do it.

**Comment by fikovnik** [comment]
I think that is too much work for little gain now so I would suggest to recode the file in R.

```sh
R -e 'saveRDS(readRDS("file"), "file.v2", version=2)'
```

Even better, we can use R to extract all necessary information from packages into something we can later read.

**Comment by programLyrique** [comment]
If it is only the encoding, I don't think it is a lot of work. 

> This format extends version 2 format by adding an identifier of the
>   current native encoding to the serialization header

(in `serialize.c`). 

No need to support ALTREP. for now.

**Comment by programLyrique** [comment]
I added some support for RDS v3 in my branch (server-rpc). It's been enough for my purpose so far.
